import React,{useEffect,useState} from 'react';
import {api,params} from './api.js';
import {Icon,Badge,Empty,Notice} from './ui.jsx';
const endpoint=(path,branch)=>`/api/staff${path}?${params({branch})}`;
const ErrorNotice=Notice;
export function Templates({branch}){
 const [templates,setTemplates]=useState([]),[error,setError]=useState(),[busy,setBusy]=useState(false),[source,setSource]=useState();
 async function load(){setTemplates(await api.request(endpoint('/templates',branch)));}
 useEffect(()=>{load().catch(setError);},[branch]);
 async function create(e){e.preventDefault();setBusy(true);setError(null);const form=e.currentTarget;const values=Object.fromEntries(new FormData(form));try{await api.request(endpoint('/templates',branch),{method:'POST',body:JSON.stringify({...values,plannedSessions:Number(values.plannedSessions),previousVersionId:source?.id})});setSource(undefined);form.reset();await load();}catch(e){setError(e);}finally{setBusy(false);}}
 async function publish(t){if(!window.confirm(`Approve ${t.name}, version ${t.revision}, for clinical use? Review the instructions before publishing.`))return;setBusy(true);setError(null);try{await api.request(endpoint(`/templates/${t.id}/publish`,branch),{method:'POST'});await load();}catch(e){setError(e);}finally{setBusy(false);}}
 return <div className="clinical-content"><ErrorNotice error={error}/><p className="muted">Clinician-authored instructions only. Publishing approves this exact version; future revisions do not change existing patient plans.</p><div className="split"><section><h3>{source?'Create next version':'Create a draft template'}</h3><form key={source?.id||'new'} onSubmit={create}><label>Name<input name="name" required maxLength={150} defaultValue={source?.name}/></label><label>Treatment type<input name="treatmentType" required maxLength={200} defaultValue={source?.treatmentType}/></label><label>Planned sessions<input name="plannedSessions" type="number" min={1} max={200} required defaultValue={source?.plannedSessions}/></label><label>Patient-facing instructions<textarea name="instructions" required maxLength={10000} rows={6} defaultValue={source?.instructions}/></label><button disabled={busy}>Save draft</button>{source&&<button type="button" className="secondary" onClick={()=>setSource(undefined)}>Cancel revision</button>}</form></section><section><h3>Template versions</h3>{!templates.length&&<Empty icon="file" compact>No clinical templates have been authored for this branch.</Empty>}{templates.map(t=><article className="clinical-card" key={t.id}><div className="card-head"><strong>{t.name} · v{t.revision}</strong><Badge value={t.state}/></div><small>{t.treatmentType&&`${t.treatmentType} · `}{t.plannedSessions} planned sessions</small><details><summary>Review instructions</summary><p className="preserve-lines">{t.instructions}</p></details><div className="form-actions">{t.state==='DRAFT'&&<button disabled={busy} onClick={()=>publish(t)}>Approve & publish</button>}<button className="secondary" onClick={()=>setSource(t)}>New version</button></div></article>)}</section></div></div>;
}
export function PatientPlans({branch,patient}){
 const [plans,setPlans]=useState([]),[templates,setTemplates]=useState([]),[error,setError]=useState(),[busy,setBusy]=useState(false);
 async function load(){const [p,t]=await Promise.all([api.request(endpoint(`/patients/${patient}/plans`,branch)),api.request(endpoint('/templates',branch))]);setPlans(p);setTemplates(t.filter(v=>v.state==='PUBLISHED'));}
 useEffect(()=>{load().catch(setError);},[branch,patient]);
 async function assign(e){e.preventDefault();setError(null);setBusy(true);const values=Object.fromEntries(new FormData(e.target));try{await api.request(endpoint(`/patients/${patient}/plans`,branch),{method:'POST',body:JSON.stringify({...values,templateVersionId:Number(values.templateVersionId)})});await load();}catch(e){setError(e);}finally{setBusy(false);}}
 async function change(plan,status){const reason=window.prompt(`Clinical reason to mark this plan ${status.toLowerCase()}:`);if(!reason?.trim())return;setError(null);setBusy(true);try{await api.request(endpoint(`/patients/${patient}/plans/${plan.id}`,branch),{method:'PATCH',body:JSON.stringify({status,version:plan.version,reason})});await load();}catch(e){setError(e);}finally{setBusy(false);}}
 return <section><h3>Treatment plans</h3><ErrorNotice error={error}/>{plans.map(p=><article className="clinical-card" key={p.id}><div className="card-head"><strong>{p.name}</strong><Badge value={p.status}/></div><small>{p.totalSessions} planned sessions · {p.startDate}</small><details><summary>Approved instructions</summary><p className="preserve-lines">{p.instructions}</p></details><PlanSessions branch={branch} patient={patient} plan={p}/>{['ACTIVE','PAUSED'].includes(p.status)&&<div className="form-actions"><button disabled={busy} className="secondary" onClick={()=>change(p,p.status==='ACTIVE'?'PAUSED':'ACTIVE')}>{p.status==='ACTIVE'?'Pause':'Resume'}</button><button disabled={busy} className="secondary" onClick={()=>change(p,'CANCELLED')}>Cancel plan</button>{p.status==='ACTIVE'&&<button disabled={busy} className="secondary" onClick={()=>change(p,'COMPLETED')}>Complete plan</button>}</div>}</article>)}{!plans.length&&<Empty icon="file" compact>No branch-assigned plans. Legacy plans need an authorized branch mapping.</Empty>}{!plans.some(p=>p.status==='ACTIVE')&&<form onSubmit={assign}><h4>Approve a patient plan</h4><label>Published template<select name="templateVersionId" required defaultValue=""><option value="" disabled>Select a reviewed template</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name} · v{t.revision}</option>)}</select></label><label>Start date<input type="date" name="startDate" required/></label><label>Patient-specific approval reason<textarea name="approvalReason" maxLength={2000} required rows={3}/></label><p className="muted">Approving copies these instructions to the patient's app. Review suitability before proceeding.</p><button disabled={busy||!templates.length}>Approve & assign plan</button></form>}</section>;
}

function PlanSessions({branch,patient,plan}) {
 const [items,setItems]=useState([]),[error,setError]=useState(),[busy,setBusy]=useState(false);
 const path=endpoint(`/patients/${patient}/plans/${plan.id}/sessions`,branch);
 async function load(){setItems(await api.request(path));}
 useEffect(()=>{load().catch(setError);},[path]);
 async function link(e){e.preventDefault();setBusy(true);setError(null);const form=e.currentTarget;const values=Object.fromEntries(new FormData(form));try{await api.request(path,{method:'POST',body:JSON.stringify({...values,appointmentId:Number(values.appointmentId)})});form.reset();await load();}catch(e){setError(e);}finally{setBusy(false);}}
 return <details><summary>Sessions ({items.length})</summary><ErrorNotice error={error}/>{items.map(s=><div className="session" key={s.id}><span className="ref">#{s.number}</span><div><strong>{s.name}</strong><small>{s.date} {s.time.slice(0,5)} · AP-{s.appointmentId}</small></div><Badge value={s.status}/></div>)}{plan.status==='ACTIVE'&&<form onSubmit={link}><label>Confirmed appointment reference (number)<input name="appointmentId" type="number" min={1} required/></label><label>Session name<input name="name" maxLength={200} required/></label><p className="muted">Reserve an appointment for this patient first. Its date and attendance will stay linked to this session.</p><button disabled={busy}>Link session</button></form>}</details>;
}
