import React,{useEffect,useState} from 'react';
import {api,params} from './api.js';
import {Icon,Avatar,Notice,Empty,Segmented,human} from './ui.jsx';
export function FollowUps({branch}) {
 const [data,setData]=useState(),[assignees,setAssignees]=useState([]),[state,setState]=useState('OPEN'),[page,setPage]=useState(0),[error,setError]=useState(),[busy,setBusy]=useState(false);
 const path='/api/staff/follow-ups';
 async function load(){setData(await api.request(`${path}?${params({branch,state,page})}`));}
 useEffect(()=>{let active=true;setData(undefined);setError(null);api.request(`${path}?${params({branch,state,page})}`).then(d=>{if(active)setData(d);}).catch(e=>{if(active)setError(e);});return()=>{active=false;};},[branch,state,page]);
 useEffect(()=>{api.request(`${path}/assignees?${params({branch})}`).then(setAssignees).catch(setError);},[branch]);
 async function create(e){e.preventDefault();setBusy(true);setError(null);const form=e.currentTarget;const values=Object.fromEntries(new FormData(form));try{await api.request(`${path}?${params({branch})}`,{method:'POST',body:JSON.stringify({...values,patientId:Number(values.patientId),assignedTo:Number(values.assignedTo)})});form.reset();await load();}catch(e){setError(e);}finally{setBusy(false);}}
 async function resolve(t,status){const resolution=window.prompt(`Reason to mark this follow-up ${status.toLowerCase()}:`);if(!resolution?.trim())return;setBusy(true);setError(null);try{await api.request(`${path}/${t.id}?${params({branch})}`,{method:'PATCH',body:JSON.stringify({state:status,version:t.version,resolution})});await load();}catch(e){setError(e);}finally{setBusy(false);}}
 return <div className="clinical-content">{error&&<Notice error={error}/>}<div className="split"><section><h3>New follow-up</h3><form onSubmit={create}><label>Patient reference (number)<input name="patientId" type="number" min={1} required/></label><label>Assigned staff<select name="assignedTo" defaultValue="" required><option value="" disabled>Select branch staff</option>{assignees.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Task<input name="title" maxLength={200} required/></label><label>Due date<input name="dueDate" type="date" required/></label><p className="muted">Use an operational description. Clinical notes belong in the treatment record.</p><button disabled={busy||!assignees.length}>Create follow-up</button></form></section><section><Segmented active={state} role="group" aria-label="Show follow-ups">{['OPEN','DONE','CANCELLED'].map(s=><button key={s} aria-pressed={state===s} onClick={()=>{setState(s);setPage(0);}}>{human(s)}</button>)}</Segmented>{!data&&!error&&<p role="status">Loading follow-ups…</p>}{data?.items?.length===0&&<Empty icon="checks" compact>No {state.toLowerCase()} follow-ups.</Empty>}{data?.items.map(t=>{const late=t.state==='OPEN'&&t.dueDate<new Date().toLocaleDateString('en-CA');return <article className="task" key={t.id}><Avatar name={t.patientName}/><div className="task-main"><strong>{t.title}</strong><div className="task-meta"><span>{t.patientName} · BP-{t.patientId}</span><span><Icon name="users" size={13}/>{t.assignee}</span></div>{t.resolution&&<p>{t.resolution}</p>}{t.state==='OPEN'&&<div className="form-actions"><button disabled={busy} onClick={()=>resolve(t,'DONE')}>Mark done</button><button disabled={busy} className="secondary" onClick={()=>resolve(t,'CANCELLED')}>Cancel</button></div>}</div><span className={`due${late?' late':''}`}><Icon name="clock" size={13}/>Due {t.dueDate}</span></article>;})}<div className="pager"><button className="secondary" disabled={!page} onClick={()=>setPage(page-1)}><Icon name="chevronLeft" size={16}/>Previous</button><button className="secondary" disabled={!data?.hasNext} onClick={()=>setPage(page+1)}>Next<Icon name="chevronRight" size={16}/></button></div></section></div></div>;
}
