import React, {useEffect,useRef,useState} from 'react';
import {api,params} from './api.js';
import {Icon,Notice,human} from './ui.jsx';
const dateNow=()=>new Date().toLocaleDateString('en-CA');
const ErrorBox=Notice;
export function BookingForm({branch,onDone,appointment}){
 const[catalog,setCatalog]=useState(),[patients,setPatients]=useState([]),[query,setQuery]=useState(''),[patient,setPatient]=useState(appointment?.patientId||''),[resource,setResource]=useState(appointment?.resourceId||''),[service,setService]=useState(appointment?.serviceId||''),[day,setDay]=useState(dateNow()),[slots,setSlots]=useState([]),[slot,setSlot]=useState(''),[error,setError]=useState(),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false);
 const submission=useRef({});
 const moving=!!appointment?.resourceId;
 useEffect(()=>{const a=new AbortController();api.request('/api/staff/catalog?'+params({branch}),{signal:a.signal}).then(setCatalog).catch(e=>{if(e.name!=='AbortError')setError(e);});return()=>a.abort();},[branch]);
 useEffect(()=>{if(appointment)return;const a=new AbortController();const timer=setTimeout(()=>api.request('/api/staff/patients?'+params({branch,query,size:25}),{signal:a.signal}).then(d=>setPatients(d.items)).catch(e=>{if(e.name!=='AbortError')setError(e);}),300);return()=>{clearTimeout(timer);a.abort();};},[branch,query,appointment]);
 useEffect(()=>{setSlots([]);setSlot('');if(!resource||!service)return;const a=new AbortController();setLoading(true);setError(null);api.request('/api/staff/availability?'+params({resourceId:resource,serviceId:service,day}),{signal:a.signal}).then(setSlots).catch(e=>{if(e.name!=='AbortError')setError(e);}).finally(()=>{if(!a.signal.aborted)setLoading(false);});return()=>a.abort();},[resource,service,day]);
 async function submit(e){e.preventDefault();setBusy(true);setError(null);const fields=Object.fromEntries(new FormData(e.target));const body=moving?{startsAt:slot,version:appointment.version,reason:fields.reason}:{patientId:Number(patient),resourceId:Number(resource),serviceId:Number(service),startsAt:slot,note:fields.note||null,requestedAppointmentId:appointment?.id||null,version:appointment?.version||0};const fingerprint=JSON.stringify(body);if(submission.current.body!==fingerprint)submission.current={body:fingerprint,key:crypto.randomUUID()};try{await api.request('/api/staff/appointments'+(moving?`/${appointment.id}/reschedule`:'')+'?'+params({branch}),{method:moving?'PATCH':'POST',headers:{'Idempotency-Key':submission.current.key},body:fingerprint});onDone();}catch(err){setError(err);}finally{setBusy(false);}}
 const timezone=catalog?.resources.find(r=>String(r.id)===String(resource))?.timezone;
 return <form onSubmit={submit}><ErrorBox error={error}/>{!appointment&&<><label>Find patient<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, email or phone"/></label><label>Patient<select required value={patient} onChange={e=>setPatient(e.target.value)}><option value="">Choose a patient</option>{patients.map(p=><option key={p.id} value={p.id}>{p.fullName} · {p.email}</option>)}</select></label></>}<div className="field-row"><label>Service<select required disabled={moving} value={service} onChange={e=>setService(e.target.value)}><option value="">Choose a service</option>{catalog?.services.map(s=><option key={s.id} value={s.id}>{s.name} · {s.durationMinutes} min</option>)}</select></label><label>Resource<select required disabled={moving} value={resource} onChange={e=>setResource(e.target.value)}><option value="">Choose a resource</option>{catalog?.resources.map(r=><option key={r.id} value={r.id}>{r.name} · {r.timezone}</option>)}</select></label></div>{catalog&&(!catalog.services.length||!catalog.resources.length)&&<p className="muted">A branch manager must configure services, resources and working hours before booking.</p>}<div className="field-row"><label>Date<input type="date" value={day} min={dateNow()} onChange={e=>setDay(e.target.value)} required/></label><label>Available time{timezone&&<small>Times are shown in {timezone}.</small>}<select required value={slot} onChange={e=>setSlot(e.target.value)} disabled={loading||!slots.length}><option value="">{loading?'Checking availability…':slots.length?'Choose an available time':'No available slots'}</option>{slots.map(s=><option key={s} value={s}>{new Intl.DateTimeFormat('en',{timeZone:timezone,hour:'2-digit',minute:'2-digit'}).format(new Date(s))}</option>)}</select></label></div><label>{moving?'Reason for reschedule':'Appointment note · optional'}<input name={moving?'reason':'note'} maxLength={500} required={moving}/></label><div className="form-actions"><button disabled={busy||!slot}>{busy?'Saving reservation…':moving?'Reschedule appointment':'Confirm appointment'}</button></div></form>;
}
export function AppointmentActions({appointment:a,branch,clinical,onChanged,onReschedule}){
 const[error,setError]=useState(),[busy,setBusy]=useState(false);
 const actions=a.status==='CONFIRMED'?['CHECKED_IN','CANCELLED','NO_SHOW']:a.status==='CHECKED_IN'&&clinical?['IN_CONSULTATION']:a.status==='IN_CONSULTATION'&&clinical?['COMPLETED']:a.status==='PENDING'?['CANCELLED']:[];
 async function change(status){if(!status)return;let reason=null;if(['CANCELLED','NO_SHOW'].includes(status)){reason=window.prompt('Reason for '+status.toLowerCase().replaceAll('_',' '));if(!reason?.trim())return;}setBusy(true);try{await api.request(`/api/staff/appointments/${a.id}/status?${params({branch})}`,{method:'PATCH',body:JSON.stringify({status,version:a.version,reason})});onChanged();}catch(e){setError(e);}finally{setBusy(false);}}
 return <div className="row-actions">{actions.length>0&&<select aria-label={`Update appointment ${a.id}`} disabled={busy} value="" onChange={e=>change(e.target.value)}><option value="">Update status</option>{actions.map(s=><option key={s} value={s}>{human(s)}</option>)}</select>}{((a.resourceId&&['CONFIRMED','PENDING'].includes(a.status))||(!a.resourceId&&a.status==='PENDING'))&&<button className="text-button" onClick={()=>onReschedule(a)}>{a.resourceId?'Reschedule':'Reserve slot'}</button>}<ErrorBox error={error}/></div>;
}
export function ScheduleSettings({branch}){
 const[catalog,setCatalog]=useState(),[error,setError]=useState(),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[selected,setSelected]=useState(''),[hours,setHours]=useState([]),[refresh,setRefresh]=useState(0);
 useEffect(()=>{api.request('/api/staff/catalog?'+params({branch})).then(setCatalog).catch(setError);},[branch,refresh]);
 useEffect(()=>{setHours([]);if(selected)api.request(`/api/staff/resources/${selected}/hours`).then(setHours).catch(setError);},[selected,refresh]);
 async function save(e,kind){e.preventDefault();setBusy(true);setError(null);setMessage('');const form=e.target,data=Object.fromEntries(new FormData(form));let path,method='POST';if(kind==='service'){data.durationMinutes=Number(data.durationMinutes);path='/api/staff/services?'+params({branch});}else if(kind==='resource'){data.branch=branch;path='/api/staff/resources';}else{data.weekday=Number(data.weekday);method='PUT';path=`/api/staff/resources/${selected}/hours`;}try{await api.request(path,{method,body:JSON.stringify(data)});setMessage('Configuration saved.');setRefresh(x=>x+1);form.reset();}catch(err){setError(err);}finally{setBusy(false);}}
 return <div className="settings-content"><ErrorBox error={error}/>{message&&<div className="success" role="status"><Icon name="check" size={16}/>{message}</div>}<div className="settings-grid"><form onSubmit={e=>save(e,'service')}><h3>Add a service</h3><p className="muted">Define a scheduling duration, not a clinical protocol.</p><label>Service name<input name="name" required maxLength={120}/></label><label>Duration in minutes<input name="durationMinutes" type="number" min={5} max={480} required/></label><button disabled={busy}>Add service</button></form><form onSubmit={e=>save(e,'resource')}><h3>Add a reservable resource</h3><p className="muted">One reservation at a time per resource.</p><label>Resource name<input name="name" required maxLength={120} placeholder="Consultation room or clinician resource"/></label><label>IANA timezone<input name="timezone" placeholder="Asia/Dubai" required/></label><button disabled={busy}>Add resource</button></form><form onSubmit={e=>save(e,'hours')}><h3>Set weekly availability</h3><p className="muted">Choose a resource, then set its opening hours per weekday.</p><label>Resource<select value={selected} onChange={e=>setSelected(e.target.value)} required><option value="">Choose a resource</option>{catalog?.resources.map(r=><option key={r.id} value={r.id}>{r.name} · {r.timezone}</option>)}</select></label><label>Weekday<select name="weekday">{['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map((d,i)=><option key={d} value={i+1}>{d}</option>)}</select></label><div className="time-pair"><label>Opens<input name="opens" type="time" required/></label><label>Closes<input name="closes" type="time" required/></label></div><button disabled={busy||!selected}>Save hours</button>{hours.length>0&&<div className="hours">{hours.map(h=><span className="ref" key={h.weekday}>{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][h.weekday-1]} · {h.opens.slice(0,5)}–{h.closes.slice(0,5)}</span>)}</div>}</form></div><h3>Service catalog</h3>{catalog?.services.length?<ul className="catalog-list">{catalog.services.map(s=><li key={s.id}>{s.name}<span>{s.durationMinutes} minutes</span></li>)}</ul>:<p className="muted">No services configured yet.</p>}</div>;
}
